apiVersion: apps/v1
kind: Deployment
metadata:
  name: abctechnologies-deployment
spec:
  selector:
    matchLabels:
      app: abctechnologies-project
  replicas: 4
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      name: abctechnologies-deployment
      labels:
        app: abctechnologies-project
    spec:
      containers:
      - image: gilbertromero/abctechnologies
        name: abctechnologies-project
        ports:
        - containerPort: 8080
