- name: Build Docker image
  hosts: web
  become: yes
  vars:
    ansible_user: root
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

  tasks:
    - name: Copy WAR file to host directory
      copy:
        src: **/*.war
        dest: /root/GradeProject/
      tags:
        - copy_war_file
    - name: Build Docker image from Dockerfile
      shell: |
        docker build -t abctechnologies /root/GradeProject/
      tags:
        - build_image
    - name: Docker create tag image
      command: docker tag abctechnologies gilbertromero/abctechnologies
    - name: Push Docker image to registry
      docker_image:
        name: abctechnologies
        tag: latest
        source: local
        repository: gilbertromero/abctechnologies
        push: yes
      tags:
        - push_image
    - name: Run Docker Container
      command: docker run -d -p 8090:8080 abctechnologies
