- name: Build Docker image
  hosts: web
  become: yes
  vars:
    ansible_user: root
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

  tasks:
    - name: Build Docker image from Dockerfile
      shell: |
        docker build -t newtomcat /root/GradeProject/
      tags:
        - build_image

    - name: Run Docker Container
      command: docker run -d -p 8090:8080 newtomcat
