- name: Build Docker image
  hosts: App
  become: yes
  vars:
    ansible_user: root
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: Build Docker image from Dockerfile
      shell: |
        docker build -t newtomcat /root/GradeProject/
      tags:
        - build_image

    - name: Run Docker Container
      docker_container:
        name: tomcatcontainer
        image: newtomcat
        state: started
        ports:
          - "8090:8080"
      tags:
        - run_container
