- name: Build Docker image
  hosts: web
  become: yes
  vars:
    ansible_user: root
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: Build Docker image from Dockerfile
      shell: |
        docker build -t newtomcat /root/GradeProject/
      tags:
        - build_image
