apiVersion: v1
kind: Service
metadata:
  name: abctechnologies-service
  labels:
    app: abctechnologies-project
spec:
  selector:
    app: abctechnologies-project
  ports:
    - port: 8080
      nodePort: 30666
      targetPort: 8080
  type: NodePort
